name: Build Docker Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get version name
      shell: bash
      run: echo "##[set-output name=name;]`echo ${GITHUB_REF#refs/tags/}`"
      id: branch

    - name: Build Docker Container
      run: docker build -t ractf/core:${{ steps.branch.outputs.name }} -t ghcr.io/ractf/core:${{ steps.branch.outputs.name }} -t ractf/core:latest -t ghcr.io/ractf/core:latest .

    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    - name: Login to Docker Hub
      run: docker login --username ractf --password ${{ secrets.password }}

    - name: Login to Github Container Registry
      run: echo ${{ secrets.ghtoken }} | docker login ghcr.io -u ${{ secrets.ghuser }} --password-stdin

    - name: Push to Docker Hub
      run: |
          docker push ractf/core:${{ steps.branch.outputs.name }}
          docker push ractf/core:latest

    - name: Push to Github Container Registry
      run: |
          docker push ghcr.io/ractf/core:${{ steps.branch.outputs.name }}
          docker push ghcr.io/ractf/core:latest
