name: Build Docker Container

on:
  push:
    branches:    
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get branch name
      shell: bash
      run: echo "##[set-output name=name;]$([ ${GITHUB_REF#refs/heads/} = git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@' ] && echo 'latest' || echo ${GITHUB_REF#refs/heads/})"
      id: branch

    - name: Cache docker layers
      uses: satackey/action-docker-layer-caching@v0.0.4
      with:
        key: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-{hash}
        restore-keys: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-

    - name: Build challenge
      run: docker build -t ractf/core:${{ steps.branch.outputs.name }} .

    - name: Login to Docker Hub
      run: docker login --username ractf --password ${{ secrets.password }}
      
    - name: Push to GitHub Packages
      run: docker push ractf/core:${{ steps.branch.outputs.name }}
